name: Setup Python
description: Setup Python

inputs:
  python-cache-type:
    default: pip
    description: python-cache-type
  python-packages:
    description: python-packages
  python-version:
    default: "3.12"
    description: python-version

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        cache: ${{ inputs.python-cache-type }}
        python-version: ${{ inputs.python-version }}

    - shell: sh
      run: python -m pip install --upgrade uv
    
    - shell: sh
      run: uv pip install --system .[${{ inputs.python-packages }}]
