name: Setup Python
description: Sets up Python environment for workflows

inputs:
  cache:
    description: Cache type to use with setup-python
    required: false
    default: pip
  version:
    description: Python version to install
    required: true
    default: "3.12"
  extra-package:
    description: Additional optional package to install
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        cache: ${{ inputs.cache }}
        python-version: ${{ inputs.version }}

    - name: Install dependencies
      shell: sh
      run: |
        python -m pip install --upgrade uv
        uv pip install --system .[${{ inputs.extra-package }}]