name: Build Nix Flake
description: Builds all packages and devShells in the flake

runs:
  using: composite
  steps:
    - name: Build packages
      shell: sh
      run: nix run github:Mic92/nix-fast-build --skip-cached --no-nom --flake ".#packages"

    - name: Build devShells
      shell: sh
      run: nix run github:Mic92/nix-fast-build --skip-cached --no-nom --flake ".#devShells"