name: Setup Nix
description: Sets up Nix environment for workflows

inputs:
  name:
    description: The name of the Cachix cache
    required: true
    default: "teamwolfyta-testing"
  skipPush:
    description: Is this a pull request?
    required: false
    default: "true"
  authToken:
    description: The Cachix auth token
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v25

    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: ${{ inputs.name }}
        skipPush: ${{ inputs.skipPush }}
        authToken: ${{ inputs.CACHIX_AUTH_TOKEN }}