name: Setup Nix
description: Setup Nix

inputs:
  cachix-auth-token:
    description: cachix-auth-token
  cachix-name: 
    default: teamwolfyta-testing
    description: cachix-name
  cachix-skip-push:
    default: ${{ false }}
    description: cachix-skip-push

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        authToken: ${{ inputs.cachix-auth-token }}
        name: ${{ inputs.cachix-name }}
        skipPush: ${{ inputs.cachix-skip-push }}
