name: Setup Nix
description: Sets up Nix environment for workflows

inputs:
  skipPush:
    description: Is this a pull request?
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v25

    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: ${{ env.CACHIX_CACHE_NAME }}
        skipPush: ${{ inputs.skipPush }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}