name: Flake Build

on: 
  push: {}
  pull_request: {}
  workflow_dispatch: {}

concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
  
jobs:
  flake_build:
    name: Build Nix Flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          skipPush: ${{ github.event_name == 'pull_request' }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        
      - name: Install nix-fast-build
        run: nix profile install nixpkgs#nix-fast-build
        
      - name: Check flake
        run: nix-fast-build --skip-cached --no-nom

      - name: Build packages
        run: nix-fast-build --skip-cached --no-nom --flake ".#packages"
  
      - name: Build dev shells
        run: nix-fast-build --skip-cached --no-nom --flake ".#devShells"