name: Cachix

on: 
  push:
    branches: 
      - main
  workflow_dispatch: {}

concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}

env:
  CACHIX_CACHE_NAME: teamwolfyta-testing

jobs:
  cachix:
    name: Cachix
    runs-on: ubuntu-latest
    if: github.repository == 'teamwolfyta/tagstudiodev_tagstudio'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      # - name: Setup Cachix
      #   uses: cachix/cachix-action@v15
      #   with:
      #     name: ${{ env.CACHIX_CACHE_NAME }}
      #     authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Flake Build
        uses: ./.github/actions/build-nix-flake
        with:
          extra-arguments: --attic-cache ${{ env.CACHIX_CACHE_NAME }}
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}