name: Flake Build

on: 
  push: {}
  pull_request: {}
  workflow_dispatch: {}

concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
  
jobs:
  flake_build:
    name: Flake Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix
        with:
          skipPush: ${{ github.event_name == 'pull_request' }}
        
      - name: Install nix-fast-build
        run: nix profile install nixpkgs#nix-fast-build
        
      - name: Flake Check
        run: nix-fast-build --skip-cached --no-nom

      - name: Build packages
        run: nix-fast-build --skip-cached --no-nom --flake ".#packages"
  
      - name: Build devShells
        run: nix-fast-build --skip-cached --no-nom --flake ".#devShells"