name: Flake Checker

on:
  push: {}
  workflow_dispatch: {}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  flake-checker: 
    name: Run Flake Checker
    if: github.repository == 'teamwolfyta/tagstudiodev_tagstudio'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-nix

      - uses: DeterminateSystems/flake-checker-action@v9