name: MyPy

on: 
  push: {}
  pull_request: {}
  workflow_dispatch: {}

concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  REVIEWDOG_VERSION: latest

jobs:
  mypy:
    name: Run MyPy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python
        with:
          python-packages: mypy

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: ${{ env.REVIEWDOG_VERSION }}
        
      - uses: tsuyoshicho/action-mypy@v4
        with:
          fail_on_error: true