name: Publish

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  workflow_dispatch: {}

concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build ${{ matrix.display-name}}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2019]
        build-type: ['', portable]
        include:
          
    uses: ./.github/workflows/build.yaml
    with: {}

  publish: {}