name: PyTest

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
  
concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  PYTEST_COVERAGE_ARTIFACT_NAME: pytest-coverage.xml

jobs:
  pytest:
    name: PyTest
    runs-on: ubuntu-24.04 # NOTE: This is pinned for some reason!
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          extra-package: pytest
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libegl1 \
            libgl1 \
            libopengl0 \
            libpulse0 \
            libxcb-cursor0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libxkbcommon-x11-0 \
            libyaml-dev \
            x11-utils

      - name: Run PyTest
        run: xvfb-run pytest --cov-report xml --cov=tagstudio

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PYTEST_COVERAGE_ARTIFACT_NAME }}
          path: coverage.xml

  report_coverage:
    name: Report Coverage
    runs-on: ubuntu-latest 
    needs: 
      - pytest
    steps:
      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PYTEST_COVERAGE_ARTIFACT_NAME }}

      - name: Report Coverage
        uses: yedpodtrzitko/coverage@main
        with:
          coverageFile: coverage.xml
          sourceDir: tagstudio/src
          thresholdAll: 0.4
          thresholdModified: 0.4
          thresholdNew: 0.4
          token: ${{ secrets.GITHUB_TOKEN }}
