name: Ruff 

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  RUFF_VERSION: 0.8.1
  
jobs:
  format:
    name: Ruff Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: format --check
          version: ${{ env.RUFF_VERSION }}

  check:
    name: Ruff Check
    runs-on: Ruff ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff check
        uses: chartboost/ruff-action@v1
        with:
          args: check
          version: ${{ env.RUFF_VERSION }}
